version: '2'
networks:
  docker0:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: "compose0"
      com.docker.network.enable_ipv6: "false"
      com.docker.network.bridge.enable_ip_masquerade: "true"
    ipam:
      driver: default
      config:
      - subnet: 172.20.0.0/24
        gateway: 172.20.0.1

services:
  osm_svk:
    container_name: osm_svk
    restart: always
    image: admik/openstreetmaps
    mem_limit: 4096m
    networks:
      docker0:
        ipv4_address: 172.20.0.253
    volumes:
      - /var/lib/docker/perm_volumes/osm_svk/mod_tile/default:/var/lib/mod_tile/default:Z
      - /var/lib/docker/perm_volumes/osm_svk/psql_data:/var/lib/postgresql/9.6/main:Z
      - /var/lib/docker/perm_volumes/osm_svk/html:/var/www/html:Z
    ports:
      - "25380:80"
